import { assignedGroupCount, BLANK_TRANSITION_DURATION_MS, buildCounterbalancedSequence, canTransition, deterministicGroupMask, estimateRefreshRate, isStimulusPhase, isTemporalSampleFrame, oppositeDirection, raisedSineOpacity, responseLatencyMs, responseRelation, resultToCsv, sampleParticleCoordinates, seededRandom, temporalDutyCycleOpacity, temporalSamplingSummary, usesAdaptationTemporalSampling, validateConfig } from './trial'
import { defaultConfig, type TrialResult } from '../types'

describe('trial logic',()=>{
  it('maps all motion directions to their opposite',()=>{expect(oppositeDirection('forward')).toBe('backward');expect(oppositeDirection('left')).toBe('right');expect(oppositeDirection('up')).toBe('down')})
  it('enforces phase transitions without a confidence phase',()=>{expect(canTransition('fixation','adaptation')).toBe(true);expect(canTransition('transition','motion-test')).toBe(true);expect(canTransition('response','complete')).toBe(true);expect(canTransition('fixation','response')).toBe(false)})
  it('uses a 200 ms blank interval between adaptation and test',()=>{expect(BLANK_TRANSITION_DURATION_MS).toBe(200)})
  it('identifies only the unobstructed stimulus-view phases',()=>{expect(isStimulusPhase('adaptation')).toBe(true);expect(isStimulusPhase('motion-test')).toBe(true);expect(isStimulusPhase('response')).toBe(false)})
  it('produces deterministic random values',()=>{const a=seededRandom(7),b=seededRandom(7);expect([a(),a(),a()]).toEqual([b(),b(),b()])})
  it('resamples a new deterministic position for every particle generation',()=>{const random=seededRandom(12);const first=sampleParticleCoordinates(defaultConfig,random);const second=sampleParticleCoordinates(defaultConfig,random);expect(second).not.toEqual(first);const replay=seededRandom(12);expect(sampleParticleCoordinates(defaultConfig,replay)).toEqual(first);expect(sampleParticleCoordinates(defaultConfig,replay)).toEqual(second)})
  it('shows exactly one frame in each three-frame adaptation cycle',()=>{expect([0,1,2,3,4,5].filter(frame=>isTemporalSampleFrame(frame,3))).toEqual([1,4]);expect([0,1,2,3,4,5].map(frame=>temporalDutyCycleOpacity(frame,3,.8))).toEqual([0,.8,0,0,.8,0])})
  it('changes successive visible-frame brightness with a gradual raised-sine envelope',()=>{expect(raisedSineOpacity(0,1,.55)).toBeCloseTo(.55);expect(raisedSineOpacity(.5,1,.55)).toBeCloseTo(1);expect(raisedSineOpacity(1,1,.55)).toBeCloseTo(.55)})
  it('never applies temporal sampling to the motion test',()=>{expect(usesAdaptationTemporalSampling('adaptation',true)).toBe(true);expect(usesAdaptationTemporalSampling('test',true)).toBe(false);expect(usesAdaptationTemporalSampling('adaptation',false)).toBe(false)})
  it('supports exact bidirectional group counts',()=>{expect(assignedGroupCount(100,0)).toBe(0);expect(assignedGroupCount(100,.5)).toBe(50);expect(assignedGroupCount(100,1)).toBe(100)})
  it('randomly assigns an exact deterministic configured split',()=>{const a=deterministicGroupMask(100,.37,1024),b=deterministicGroupMask(100,.37,1024);expect([...a]).toEqual([...b]);expect([...a].reduce((sum,value)=>sum+value,0)).toBe(37)})
  it('classifies reports relative to adaptation without correctness scoring',()=>{expect(responseRelation('backward','forward')).toBe('opposite-to-adaptation');expect(responseRelation('forward','forward')).toBe('same-as-adaptation');expect(responseRelation('unsure','forward')).toBe('unsure')})
  it('estimates refresh rate from stable frame intervals',()=>{expect(estimateRefreshRate([16.6,16.7,16.7])).toBeCloseTo(59.9,1);expect(estimateRefreshRate([])).toBeNull()})
  it('builds a balanced sequence using exactly the operator-selected proportion',()=>{const base={...defaultConfig,oppositeDirectionShare:.37};const a=buildCounterbalancedSequence('P002',base),b=buildCounterbalancedSequence('P002',base);expect(a.trials.map(t=>[t.condition,t.config.direction,t.config.cockpitEnabled,t.config.concentricGuidesEnabled])).toEqual(b.trials.map(t=>[t.condition,t.config.direction,t.config.cockpitEnabled,t.config.concentricGuidesEnabled]));expect(a.trials).toHaveLength(8);expect(a.trials.every(t=>t.config.oppositeDirectionShare===.37)).toBe(true);expect(new Set(a.trials.map(t=>t.condition))).toEqual(new Set(['bidirectional-test']))})
  it('treats 0 and 100 percent as endpoints rather than injecting them into other sequences',()=>{expect(buildCounterbalancedSequence('P1',{...defaultConfig,oppositeDirectionShare:0}).trials.every(t=>t.condition==='same-only-control')).toBe(true);expect(buildCounterbalancedSequence('P1',{...defaultConfig,oppositeDirectionShare:1}).trials.every(t=>t.condition==='opposite-only-control')).toBe(true)})
  it('only marks WebXR predicted display-time sampling as display-frame validated',()=>{expect(temporalSamplingSummary([0,11.1,22.2],1,'webxr-predicted-display-time').validatedAgainstDisplayFrames).toBe(true);expect(temporalSamplingSummary([0,16.7,33.4],1,'desktop-raf-estimate').validatedAgainstDisplayFrames).toBe(false)})
  it('measures response latency from the response prompt and rejects invalid origins',()=>{expect(responseLatencyMs(1000,1650.4)).toBe(650);expect(responseLatencyMs(0,1650)).toBe(0);expect(responseLatencyMs(2000,1900)).toBe(0)})
  it('validates configurable safe ranges',()=>{expect(validateConfig({...defaultConfig,oppositeDirectionShare:.37})).toBe(true);expect(validateConfig({...defaultConfig,particleCount:3})).toBe(false);expect(validateConfig({...defaultConfig,oppositeDirectionShare:1.1})).toBe(false);expect(validateConfig({...defaultConfig,particleSize:.5})).toBe(false);expect(validateConfig({...defaultConfig,particleNearDistance:10,particleFarDistance:10.5})).toBe(false);expect(validateConfig({...defaultConfig,particleNearDistance:4,particleFarDistance:28})).toBe(true)})
  it('serializes protocol identity, event integrity and display-frame validation to CSV',()=>{const result:TrialResult={id:'t1',sessionId:'s1',participantId:'P1',sequenceId:'q1',trialIndex:0,blockIndex:0,condition:'bidirectional-test',timestamp:'2026-01-01',config:{...defaultConfig,oppositeDirectionShare:.37,adaptationTemporalSamplingEnabled:true},maeConsistentDirection:'backward',response:'backward',responseRelation:'opposite-to-adaptation',responsePromptLatencyMs:500,actualAdaptationDurationMs:20010,actualMotionTestDurationMs:5010,frameIntervals:[16.7],displayCalibration:{viewingDistanceCm:null,physicalScreenWidthCm:null,visualAngleCalibrated:false,estimatedRefreshRateHz:59.9,refreshRateValidated:false,deviceTimingValidated:false,viewportWidthPx:1280,viewportHeightPx:720,devicePixelRatio:2},warnings:[],aborted:false,events:[{type:'response-selected',atMs:1,phase:'response'}],focusLossCount:0,hiddenCount:0,temporalSamplingValidation:{scheduler:'desktop-raf-estimate',validatedAgainstDisplayFrames:false,observedFrameCount:3,visibleFrameCount:1,observedDutyCycle:1/3,medianFrameIntervalMs:16.7,effectiveVisibleRateHz:19.96}};const csv=resultToCsv([result]);expect(csv).toContain('sessionId');expect(csv).toContain('condition');expect(csv).toContain('responsePromptLatencyMs');expect(csv).toContain('displayFrameValidated');expect(csv).toContain('focusLossCount');expect(csv).not.toContain('confidence');expect(csv).toContain('0.37');expect(csv).toContain('opposite-to-adaptation')})
})
